/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package employeetest;

import java.text.DecimalFormat;

/**
 * CSCI 2001-51
 * 3.14 Employee Class Assignment
 * 
 * Has buttons to show one of two employee.
 * Has another button to give a raise.
 * 
 * @author Kou Xiong
 */
public class EmployeeForm extends javax.swing.JFrame {

    // make two Employee objects
    Employee firstEmp = new Employee("Kou", "Xiong", 5333.02);
    Employee secondEmp = new Employee("Lee", "Vang", 6543.25);
    
    // have two decimal places
    DecimalFormat dFormat = new DecimalFormat("0.00");
    
    // booleans used for giving a raise to the appropriate employee
    boolean first = false;
    boolean second = false;


    public EmployeeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameText = new javax.swing.JLabel();
        lastNameText = new javax.swing.JLabel();
        annSalaryText = new javax.swing.JLabel();
        firstEmpButton = new javax.swing.JButton();
        secEmpButton = new javax.swing.JButton();
        raiseButton = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        annSalaryLabel = new javax.swing.JLabel();
        monSalaryLabel = new javax.swing.JLabel();
        monSalaryText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("EmployeeTest"); // NOI18N

        firstNameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lastNameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        annSalaryText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        firstEmpButton.setText("Employee 1");
        firstEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstEmpButtonActionPerformed(evt);
            }
        });

        secEmpButton.setText("Employee 2");
        secEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secEmpButtonActionPerformed(evt);
            }
        });

        raiseButton.setText("Give a raise!");
        raiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseButtonActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastNameLabel.setText("Last Name:");

        annSalaryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        annSalaryLabel.setText("Annual Salary:");

        monSalaryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monSalaryLabel.setText("Monthly Salary:");

        monSalaryText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(annSalaryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annSalaryText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monSalaryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monSalaryText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(secEmpButton)
                                    .addComponent(firstEmpButton))
                                .addGap(54, 54, 54)
                                .addComponent(raiseButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameText)
                    .addComponent(firstNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monSalaryLabel)
                    .addComponent(monSalaryText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annSalaryLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(firstEmpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secEmpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(raiseButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstEmpButtonActionPerformed
        
        // display the first employee's information
        this.firstNameText.setText(firstEmp.getFirstName());
        this.lastNameText.setText(firstEmp.getLastName());
        this.monSalaryText.setText("$" + dFormat.format(firstEmp.getSalary()));
        this.annSalaryText.setText("$" + dFormat.format(firstEmp.getSalary() * 12));
        
        first = true;
        second = false;
    }//GEN-LAST:event_firstEmpButtonActionPerformed

    private void secEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secEmpButtonActionPerformed
        
        // display the second employee's information
        this.firstNameText.setText(secondEmp.getFirstName());
        this.lastNameText.setText(secondEmp.getLastName());
        this.monSalaryText.setText("$" + dFormat.format(secondEmp.getSalary()));
        this.annSalaryText.setText("$" + dFormat.format(secondEmp.getSalary() * 12));
        
        first = false;
        second = true;
    }//GEN-LAST:event_secEmpButtonActionPerformed

    private void raiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseButtonActionPerformed
        
        // give a 10% raise to the first employee
        if (first == true)
        {
            firstEmp.setSalary( firstEmp.getSalary() * 1.1);
            this.monSalaryText.setText("$" + dFormat.format(firstEmp.getSalary()));
            this.annSalaryText.setText("$" + dFormat.format(firstEmp.getSalary() * 12));
        }
        
        // give a 10% raise to the second employee
        if (second == true)
        {
            secondEmp.setSalary( secondEmp.getSalary() * 1.1);
            this.monSalaryText.setText("$" + dFormat.format(secondEmp.getSalary()));
            this.annSalaryText.setText("$" + dFormat.format(secondEmp.getSalary() * 12));
        }
    }//GEN-LAST:event_raiseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel annSalaryLabel;
    private javax.swing.JLabel annSalaryText;
    private javax.swing.JButton firstEmpButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JLabel monSalaryLabel;
    private javax.swing.JLabel monSalaryText;
    private javax.swing.JButton raiseButton;
    private javax.swing.JButton secEmpButton;
    // End of variables declaration//GEN-END:variables
}
